from __future__ import annotations

from pathlib import Path
from typing import Any


class Error(Exception): ...


class Browser:
    def new_context(self, **kwargs: Any) -> BrowserContext: ...
    def close(self) -> None: ...


class BrowserContext:
    def new_page(self) -> Page: ...
    def storage_state(self, *, path: str | Path) -> dict[str, Any]: ...


class BrowserType:
    def launch(self, *, headless: bool) -> Browser: ...


class Page:
    url: str
    def goto(self, url: str, **kwargs: Any) -> object: ...
    def content(self) -> str: ...
    def locator(self, selector: str) -> Locator: ...


class Locator:
    @property
    def first(self) -> Locator: ...
    def count(self) -> int: ...
    def fill(self, value: str) -> None: ...
    def click(self) -> None: ...


class Playwright:
    chromium: BrowserType


class PlaywrightContextManager:
    def __enter__(self) -> Playwright: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> object: ...


def sync_playwright() -> PlaywrightContextManager: ...
